name: cookie_store
description: Manages cookies in accordance with RFC 6265
version: 0.4.0
homepage: https://github.com/egefeyzioglu/cookie_store

environment:
  sdk: ^3.7.2

dependencies:
  http: ^1.1.0
  meta: ^1.9.0
  punycoder: ^0.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.3
